stages:
- name: Build
  steps:
  - runScriptConfig:
      image: 10.38.14.45/library/jenkins-slave:jdk8
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher/tomcat8:v3.0
      pushRemote: true
      registry: 10.38.14.45
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy.yaml
timeout: 60
notification: {}
